### ISSUE TITLE
Rate limit Header action does not add requested header 

### ISSUE THREAD

**Issue by yanushg** [curiefense/curiefense#412]
**Describe the bug**
When using header as action we do not add header 
**To Reproduce**
1. Go to rate limit and add header as action use "test" for example 
2. attach to url and publish 

**Expected behavior**
Header should be added

**Comment by bartavelle** [comment]
Headers are not implemented yet because of https://github.com/curiefense/curiefense/issues/390

**Comment by bartavelle** [comment]
Should be fixed by #463

**Comment by bartavelle** [comment]
Should be OK now

**Comment by yanushg** [comment]
Created a new issue related to it - still dont have headers when choosing header action

**Comment by yanushg** [comment]
Not working when adding the header 
Hope it will be fixed when we change FE conf for header action

**Comment by bartavelle** [comment]
Header actions work for me, I tested tag rules, rate limits, and flow control. One thing that can happen, perhaps, is that it is possible to create url maps that will match no requests, which result in an automatic accept, with no headers being added.

**Comment by semharel** [comment]
@bartavelle What syntax did you use to fill out the header field?

**Comment by bartavelle** [comment]
@semharel Not sure I understand the question, but if it is about the configuration file format, I expect an object where keys are header names, and values are header values.

**Comment by olgasobolevsky** [comment]
Global filters, action:Header doesn't work - don't see header, don't see tag of the rule in "tags".

**Comment by bartavelle** [comment]
This is also an old bug : the current field for header action makes no sense as a single string. The configuration should be as described in the message from Nov 16.
